simulation:
  duration: 3600  # seconds
  network:
    delay:
      mars_to_orbiter: 180  # seconds
      orbiter_to_relay: 600  # seconds
      relay_to_earth: 180  # seconds
    error_rate: 0.3  # 30% packet loss
    disruption_rate: 0.3  # 30% chance of disruption per link
visualization:
  node_colors:
    default: "lightblue"
    active: "red"
    completed: "green"
  edge_colors:
    default: "gray"
    active: "green"
  node_size: 500
  figure_size: [10, 8]